# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFoqQfPPqgQEmNc3OHJ-JGSEVwDTRQ8w
"""

from google.colab.patches import cv2_imshow
import cv2
import numpy as np
import os

image_path = 'colors.jpg'
if not os.path.exists(image_path):
    print(f"Error: File not found at path {image_path}")
else:
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image from {image_path}")
    else:
      image = cv2.imread(image_path)

if image is None:
    print(f"Error: Unable to load image from {image_path}")
else:
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    lower_orange = np.array([0, 100, 100])
    upper_orange = np.array([20, 255, 255])

    orange_mask = cv2.inRange(hsv, lower_orange, upper_orange)
    kernel = np.ones((5, 5), np.uint8)
    orange_mask = cv2.dilate(orange_mask, kernel, iterations=1)
    orange_mask = cv2.erode(orange_mask, kernel, iterations=1)

    result = cv2.bitwise_and(image, image, mask=orange_mask)

    cv2_imshow(image)
    cv2_imshow(orange_mask)
    cv2_imshow(result)